DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS term_scores;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS terms;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS classes;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS subjects;
