// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error)
	DeleteTeacher(ctx context.Context, id int32) error
	GetTeacher(ctx context.Context, id int32) (Teacher, error)
	ListTeachers(ctx context.Context, arg ListTeachersParams) ([]Teacher, error)
	UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (Teacher, error)
}

var _ Querier = (*Queries)(nil)
